# This is a basic workflow to help you get started with Actions

name: BUILD-JAX
# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12

        
      - name: Clone google/jax
        uses: whyakari/github-repo-action@v3.1
        with:
          # Repository Owner
          owner: google
          # Repository name
          repository: jax
          
      - name: Python Dependency Installation
        uses: insightsengineering/pip-action@v2.0.1
        with:
          # Path to requirements.txt file
          packages: |
            absl-py
            ipython
            sphinx
            myst-nb
            flatbuffers
            pytest
            pytest-xdist
            matplotlib
            scikit-learn
            numpy
          
      - name: Start building
        run: |
          cd jax
          ls -la
          python3 build/build.py --enable_cuda --cuda_compute_capabilities=sm_87 --cuda_version=12.4 --cudnn_version=8.9.4 --target_cpu=aarch64
